Wert1 = float(input("Bitte Wert eins eingeben: "))
Wert2 = float(input("Bitte Wert eins eingeben: "))
print(type(Wert1))
print(type(Wert2))
print("Summe "+ str(Wert1+Wert2))
print("Dif "+ str(Wert1-Wert2))
print("Mult "+ str(Wert1*Wert2))
print("Div "+ str(Wert1/Wert2))